### ISSUE TITLE
Tests three and four want the method named differently than the lesson says.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/javascript-bind-lab#3]
The lesson asks for a method named tick but the tests are expected the method to be named startTicking. Without changing the method name tests 3 and 4 won't pass.

**Comment by pickledyamsman** [comment]
cc @aturkewi @AnnJohn

**Comment by AnnJohn** [comment]
@thomastuts can you review the issue above and double-check the lab? thanks!

**Comment by thomastuts** [comment]
Thanks for reporting this, @pickledyamsman! This was fixed in #4 and an extra commit in the `solution` branch.
