### ISSUE TITLE
A different lab is being cloned to the react-000 batch

### ISSUE THREAD

**Issue by jjseymour** [learn-co-curriculum/javascript-bind-lab#5]
https://github.com/learn-co-students/javascript-bind-lab-react-000

The lab that opens up has the same header:

"JavaScript bind() Lab"

But it starts with `Pokemon` instead of the intended `digitalclock`

---

---

**_The ReadMe on Learn:_**
# JavaScript bind() Lab
## Objectives
1. Practice using `bind()`
2. Explain when to use `bind()`
## Tick, tock...

![Old clock](https://media.giphy.com/media/JUvTQ9K4QM6vC/giphy.gif)

That's it. We've had to repair this old clock too many times now. Let's create a digital one instead!
1. Create an object called `digitalClock`
2. This object should have two properties:
   1. `time`: the current time in _seconds_, rounded off (Hint: take a look at `Date`)
   2. `tick`: a method that increases the `time` property with one second every second. Use `.bind()` or ES2015 arrow
      functions to correctly set the property!
## So much for free speech

![Fox Censor](https://media.giphy.com/media/NZ1e0alYFBKh2/giphy.gif)

Let's automate the censoring process for Fox TV!
1. Create a function called `censor`. This function takes two arguments: the word being censored, and the string that
   should be sanitized. Don't worry about case matching for this exercise.
2. The `censor` function should return the input string, with the censored word being replaced with `'BLEEP'`.
3. Create a `violenceCensor` function (using `.bind()` and the `censor()` function) that will censor the word `'violence'`.
4. Create a `drugsCensor` function (using `.bind()` and the `censor()` function) that will censor the word `'drugs'`.

---

---

**_The ReadMe the GitHub button opens:_**
# JavaScript bind() Lab
## Objectives
1. Practice using `bind()`
2. Explain when to use `bind()`
## Overview

`bind()` can be a bit wonky to get used to, so we should give students plenty of
practice.

Maybe we have some Pokémon

``` javascript
class Pokemon {
  // `evolutions` might be an object with level-name pairs
  constructor(name, level, evolutions) {
    this.name = name
    this.level = level
    this.evolutions = evolutions
  }

  attemptEvolution() {
    const evolution = this.evolutions[this.level]

    if (evolution &&
        confirm(`${this.name} is about to evolve into ${evolution} — is that okay?`)) {
      alert(`${this.name} is evolving!`)

      // We could also do this with `bind()`!
      setTimeout(() => {
        alert(`${this.name} evolved into ${evolution}!`)
        this.name = evolution
      }, 1000)
    }
  }

  levelUp() {
    this.level = this.level + 1

    this.attemptEvolution()
  }
}
```

Note that the evolution function can be fixed with `bind()` or an arrow function
— we should show students both solutions (the arrow function is probably
preferable in this case, though).

But what if we have a Pokémon that evolves with a Moon Stone?

``` javascript
function useMoonStone() {
  const level = this.level

  this.level = 'moonStone'

  this.attemptEvolution()

  this.level = level
}
```

This function obviously won't work out of the box, but we can use it like so

``` javascript
const clefairy = new Pokemon('Clefairy', 2, { moonStone: 'Clefable' })

clefairy.evolve = useMoonStone.bind(clefairy)

clefairy.evolve()
```

(This is super contrived, but kind of fun, right?)

**Comment by AnnJohn** [comment]
redeployed the lab and that fixed the issue. thanks!
